# General settings
quarkus.log.level=INFO
%test.quarkus.log.level=INFO
%dev.quarkus.log.level=INFO
quarkus.native.native-image-xmx=5G

# Hibernate ORM settings 
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.multitenant=SCHEMA

# SCHEMA Tenant Configuration (environment variable expansion is used to facilitate docker-compose setup)
quarkus.datasource.jdbc.max-size=8
quarkus.datasource.jdbc.min-size=2
quarkus.flyway.schemas=base,mycompany
quarkus.flyway.locations=schema
quarkus.flyway.migrate-at-start=true
